name: .NET Core Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'

    - name: List files in the repository (for debugging)
      run: |
        echo "Listing files in the repository"
        ls -R

    - name: Restore dependencies
<<<<<<< HEAD
      run: |
        cd SmartLocktests
        dotnet restore SmartLocktests.csproj

    - name: Build project
      run: |
        cd SmartLocktests
        dotnet build SmartLocktests.csproj --configuration Release --verbosity detailed

    - name: Run tests
      run: |
        cd SmartLocktests
        dotnet test SmartLocktests.csproj --configuration Release --verbosity detailed
=======
      run: dotnet restore ./SmartLocktests/SmartLockTests.csproj

    - name: Build project
      run: dotnet build ./SmartLocktests/SmartLockTests.csproj --configuration Release --verbosity detailed

    - name: Run tests
      run: dotnet test ./SmartLocktests/SmartLockTests.csproj --configuration Release --verbosity detailed
>>>>>>> a8e8d6fb5fa087fa38d44fa90280d41596452b5a
