name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: List files in repository for debugging
        run: |
          echo "Listing all files in the repository"
          ls -R # Recursively list files and directories

      - name: Restore dependencies
        run: dotnet restore ./SmartlockTests/SmartLockTests.csproj

      - name: Build the project with detailed logs
        run: dotnet build ./SmartlockTests/SmartLockTests.csproj --configuration Release --verbosity detailed

      - name: Run tests with detailed logs
        run: dotnet test ./SmartlockTests/SmartLockTests.csproj --configuration Release --verbosity detailed
